# Workshop configuration
title: "BIRN Summer School 2025 Data Journalism"
description: "Learn to scrape, extract and analyze data using Python"
github_repo: "jsoma/2025-birn"
github_branch: "main"

# Workshop metadata
author: "Jonathan Soma"
organization: "Balkan Investigative Reporting Network Summer School"
date: "2025"

# Sections to process
sections:
  - title: "Adv Data Journalism I: Structured Data"
    folder: "structured-data"
    slides: "structured-data/structured-data.pdf"
  - title: "AI Do's and Don't"
    folder: "ai-dos-donts"
    slides: "ai-dos-donts/-ai-dos-donts.pdf"
  - title: "Adv Data Journalism II: Unstructured Data"
    folder: "unstructured-data"

# Publishing options
output_dir: "docs"
index_template: |
  # {{ title }}
  
  **Jonathan Soma**, Columbia University

  **Contact:** [js4571@columbia.edu](mailto:js4571@columbia.edu) • [@dangerscarf](https://x.com/dangerscarf)
  
  **Sites:** [Lede Program](https://ledeprogram.com/) • [jonathansoma.com](https://jonathansoma.com/) • [Practical AI for Investigative Journalism](https://www.youtube.com/playlist?list=PLewNEVDy7gq1_GPUaL0OQ31QsiHP5ncAQ) • [Bad PDFs](https://badpdfs.com/)

  {{ description }}
    
  {{ notebooks }}
  
  ---
  
  *Created for {{ organization }} by {{ author }}*